triggers:
  - type: page_open
  - keyword: start

steps:
  # TODO: move this to button trigger
  - user_set:
      id: u-12345
  - (auth)
  - flow: flow.auth.check
  - if: (@ flow.result )
    then: next
    else: end

  - (welcome)
  - say: Hi (@ user.name ), I'm (@ config.store.name )'s digital assistant! Thank
      you for visiting! How can I help you today?
    quick_replies:
      - text: Show Orders
        action:
          flow: flow.order.list
          transfer: true
      - text: Get Refund
        action:
          flow: flow.order.refund
          transfer: true
      - text: Find Store
        action:
          flow: flow.store.locator
          transfer: true
