triggers:
  - page_open
  - regex: ^user_(.*)$
    action:
      jump: regex

steps:
  - (page)
  - if: (@ flow.context.get("shopify_customer_id"))
    then: next
    else:
      flow: flow.start
      transfer: true

  - flow_set:
      user_id: (@ flow.context.shopify_customer_id)

  - jump: check

  - (regex)
  - flow_set:
      user_id: (@ flow.groups[0] )
  - jump: check

  - (check)
  - flow: flow.auth.check
    data:
      user_id: (@ flow.user_id )

  - flow: flow.start
