triggers:
  - button_id: .page-open
    action:
      jump: page
  - regex: ^user_(.*)$
    action:
      jump: regex

steps:
  - (page)
  - flow_set:
      user_id: (@ flow.event.data.context.user_id )
  - jump: check

  - (regex)
  - flow_set:
      user_id: (@ flow.groups[0] )
  - jump: check

  - (check)
  - flow: flow.auth.check
    data:
      user_id: (@ flow.user_id )
  - flow: flow.start
