triggers:
  - keyword: product_get
steps:
  - ask: What's the product id
  - flow_set: product_id

  - type: meya.shopify.component.product.get
    product_id: (@ flow.product_id | int)
    integration: integration.shopify

  - say: (@ flow.result | string)
